### ISSUE TITLE
Google colab

### ISSUE THREAD

**Issue by Randy-H0** [zanilzanzan/DreamBooth#1]
Hi there! Is there any google colab to use to 'train' this? Does it work well with stable diffusion?

How long does it take to train on your equipment? I've tried this other thing called textual inversion but the results aren't so great.

Thanks for your time!

**Comment by soenmezanil** [comment]
Hey there, @Randy1435! There is currently no google colab for training the model. The models that are used in combination are quite large, and currently, traning with the default Stable Diffusion model (sd-v1-4-full-ema) on 512x512 inputs requires ~38GB of GPU memory. As far as I know, google colab  doesn't provide such powerful GPUs. Instead, I am use [vast.ai](https://vast.ai/?gclid=CjwKCAjwm8WZBhBUEiwA178UnKc7qBJt3DCRScXxEXXTzBQmliVc5wvvnNYp6ZznsCmJ6tBmJqa2ThoC6KAQAvD_BwE) instances with Nvidia A6000 GPUs (48BG memory each) based on [this comment](https://github.com/XavierXiao/Dreambooth-Stable-Diffusion/issues/4#issuecomment-1246140407).

One training session with about 1000 iterations takes around 15 minutes on an A6000-powered vast.ai instance. Since inference for 512x512 outputs doesn't require nearly as much memory as training, you can download your model weights from the vast.ai instance and run the inference locally. I don't remember how much memory inference occupies precisely, but I am able to run it on an RTX 2080 Ti, with 11GB memory. 

When it comes to the costs; training on the VM, data storage and transfer costs add up to $1 on average. Yes, vast.ai quotes you on the amount of data you transfer in and out, and the resulting model is about 12GB in size. [This repository](https://github.com/prettydeep/Dreambooth-SD-ckpt-pruning) provides a script to prune your resulting model weights on the VM (down to ~3GB), so that the cost related to download would be reduced. I, personally, haven't experimented with that yet, but I will be updating the instructions on the readme soon and will include this as well.

The results in comparison to [textual inversion](https://github.com/rinongal/textual_inversion): I haven't compared textual inversion and colab performance extensively. So I won't be able to comment on that. However, I personally find some of the DreamBooth results simply mind-blowing. I have trained only a few models on portraits, and on multiple occasions, the outputs made me think that we might be living in a simulation. :) If you are curious, you should definitely give this a try.

Thanks for the interest!

**Comment by Randy-H0** [comment]
Hi! I found a really good colab!

**Comment by Randy-H0** [comment]
https://colab.research.google.com/github/ShivamShrirao/diffusers/blob/main/examples/dreambooth/DreamBooth_Stable_Diffusion.ipynb
